### ISSUE TITLE
Graphics owner

### ISSUE THREAD

**Issue by kyledovey** [maierfelix/PokeMMO#4]
Hi, Kyledove here.
I'm the creator of tileset 0.png in the img folder and also some other assets such as the icons.

These assets have been taken from my existing Pokemon mmo game.

These are fully original assets that have been taken without permission and therefore should be removed.
Thank you.

**Comment by Salakar** [comment]
That's a shame, they're awesome and work so well with this project @kyledovey - are you not interested in collab - it is all open source? The author hasn't tried to claim credit for the tilesets and has linked directly to your dA profile right at the top of the readme. This project is currently trending on Github :

![image](https://cloud.githubusercontent.com/assets/5347038/14894383/46eee9ee-0d6b-11e6-9e8a-69aa27295e82.png)

You'd also get page views from this i'd imagine, I did stalk you and watch you on dA because of this :)

But i'm not the author, just a random passer by

**Comment by maierfelix** [comment]
Graphics removed, check again.

**Comment by kyledovey** [comment]
Thanks for taking them down. I'm not really interested in private work for a game with personal friends to go open source at the moment, though maybe it will change in the future.

I appreciate the credit but that still doesn't give right to use work without permission. Thanks for understanding maierfelix and good luck!

**Comment by Salakar** [comment]
@kyledovey Thanks for being polite about it and not a douche, is a common occurrence these days. 

Good luck and keep up the cool art! 👍
